# 主题指向
theme: Scroll

# 网站名称
title: 陈陈菌博客
# 首页小标题
subtitle: ''
# 首页描述
description: '首页描述'
# 首页关键字
keywords: 首页关键字

# 作者
author: ChenJieHai

# 网站地址
url: https://chenjiehai.gitee.io
# 站点根目录地址
root: /
# 文章url规则(需要在文章抬头中定义 "id: xxx" )    
permalink: :id.html

# 首页图片封面
imageCover: background.jpg

# 评论
valine:
  el: '#vcomments'
  appId: ''
  appKey: ''

# 搜索
search:
  path: search.xml
  field: post

# 首页最大文章数
per_page: 10
pagination_dir: page

# 是否生成文章资源文件夹（与 md 名称一致）
post_asset_folder: true

# 部署
deploy:
  type: ''
