# 主题指向                     
theme: Scroll                   
# 博客标题                     
title: 陈陈菌的博客              
# 作者                         
author: ChenJieHai            
# 站点url                      
url: https://chenjiehai.gitee.io       
# 站点目录                     
root: /                        
# 文章url规则(需要在文章抬头中定义 "id: xxx" )                 
permalink: :id.html           



# 归档页面指向
archivesRoot: /archive/
# 关于页面指向(可自定义正文)
aboutRoot: /about/
# 分类页面指向
categoryRoot: /category/
# 标签页面指向
tageRoot: /tage/
# 留言页面指向
lyRoot: /ly/

# 关于页面的头像
aboutImage: '/favicon.ico'
# 关于页面QQ帐号
QQ: ***
# 关于页面GitHub用户名
GitHub: ****
# 关于页面邮箱帐号
Email: ***@qq.com

# 显示页面数
per_page: 4
pagination_dir: page

# 指定资源目录
source_dir: source
# 是否生成文章资源文件夹（与 md 名称一致）
post_asset_folder: true

# 评论
valine:
  el: '#vcomments'
  appId: ''
  appKey: ''

# 首页描述（SEO）
description: '首页描述'
keyword: 首页关键字

# 部署 
deploy:
  type: 
  repo: 
  branch: 
